=== Aristide111/Aristide111-XML-encoding-1802-Louvre-exhibition-V2/publiciste.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT element (metadata,body) >

<!ELEMENT metadata (production,transcription,text)>


<!ELEMENT production (author,publication,date) >

<!ELEMENT author (name+,firstname+)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT firstname (#PCDATA) >
<!ELEMENT publication (publishername,publisherplace?,publisherdate) >
<!ELEMENT publishername (#PCDATA) >
<!ELEMENT publisherplace (#PCDATA) >
<!ELEMENT publisherdate EMPTY>
<!ATTLIST publisherdate when CDATA #REQUIRED>
<!ATTLIST publisherdate calendar (julian | gregorian | chinese | other) #REQUIRED>
<!ELEMENT date EMPTY>
<!ATTLIST date when CDATA #REQUIRED>
<!ATTLIST date calendar (julian | gregorian | chinese | other) #REQUIRED>



<!ELEMENT transcription (author,date,place,accessibility?,operation,precision,project)>

<!ELEMENT place (#PCDATA) >
<!ELEMENT accessibility (#PCDATA) >
<!ELEMENT operation (#PCDATA) >
<!ELEMENT precision (#PCDATA) >
<!ELEMENT project (#PCDATA) >

<!ELEMENT text (conservation?, identity,materialsituation?,content) >

<!ELEMENT conservation (country,city,institution)>

<!ELEMENT institution (institutionname,departement,id,acquisition) >
<!ELEMENT institutionname (#PCDATA) >
<!ELEMENT acquisition (date,context) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT departement (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT context (#PCDATA) >

<!ELEMENT identity (title?,exlibris?,addition?) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT exlibris (#PCDATA) >
<!ELEMENT addition ( marginalia?, pagination?, stamp?) >
<!ELEMENT marginalia (#PCDATA) >
<!ELEMENT pagination (#PCDATA) >
<!ELEMENT stamp (#PCDATA) >
<!ELEMENT materialsituation (material?,binding?) >
<!ELEMENT binding (material,period) >
<!ELEMENT material (#PCDATA) >
<!ELEMENT period (#PCDATA) >
<!ELEMENT content (length?,style,goal) >
<!ELEMENT length (#PCDATA) >
<!ELEMENT style (#PCDATA) >
<!ELEMENT goal (#PCDATA) >

<!ELEMENT body (part+,marginalia?) >
<!ELEMENT part (sentence+) >
<!ELEMENT sentence (#PCDATA | name | place | piece)* >
<!ELEMENT piece (#PCDATA) >

=== Aristide111/Aristide111-XML-encoding-1802-Louvre-exhibition-V2/publiciste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "publiciste.dtd">

<element>
    <metadata>
        
        <production>
            <author>
                <name>Curtelin</name>
                <firstname>Aristide</firstname>
            </author>
            <publication>
                <publishername>Curtelin</publishername>
                <publisherplace>Paris</publisherplace>
                <publisherdate when="2025" calendar="gregorian"/>
            </publication>
            <date when="2025" calendar="gregorian"/>
        </production>
        
        <transcription>
            <author>
                <name>Curtelin</name>
                <firstname>Aristide</firstname>
            </author>
            <date when="2025" calendar="gregorian"/>
            <place>Paris</place>
            <accessibility>free</accessibility>
            <operation>transcription</operation>
            <precision>accurate</precision>
            <project>scholar exam</project>
        </transcription>
        
        <text>
            <conservation>
                <country>France</country>
                <city>Paris</city>
                <institution>
                    <institutionname>Bibliothèque Nationale de France</institutionname>
                    <departement>manuscript</departement>
                    <id>ark:/12148/btv1b10527793s</id>
                    <acquisition>
                        <date when="1802" calendar="gregorian"/>
                        <context>Depôt Légal</context>
                    </acquisition>
                </institution>
            </conservation>
            <identity>
                <title>
                    Exposition du 9. mars 1802. journal du publiciste</title>
                <addition>
                    <marginalia>yes</marginalia>
                    <pagination>yes</pagination>
                    <stamp>yes</stamp>
                </addition>
            </identity>
            <materialsituation>
                <material>paper</material>
            </materialsituation>
            <content>
                <length>4 pages</length>
                <style>press article</style>
                <goal>art description</goal>
            </content>
        </text>
    </metadata>
    
    <body>
        <part>
            <sentence> Exposition du 9 mars 1802 journal du publiciste. </sentence> 
        </part> 
        <part>
            <sentence>n voit au <place>musée central des arts</place> une nouvelle exposition de tableaux, parmi les quels on distingue plusieurs excellentes productions d'<name>andrea del Sarto de Carrache</name> de <name>Vaniyek</name> de <name>Rubens</name> de <name>Paul Veronese</name> du <name>titien </name>et de r<name>aphael.</name></sentence>
            <sentence>le <piece>martyre de st pierre , dominicain</piece>, regardé comme le chef d'oeuvre du <name>titieu </name>et le precieux tableau de <name>raphael,</name> <piece>la vierge au Donaiataire</piece>, qui se trouvait a <place>foliguo,</place> s'étant trouvé en très mauvais etat, le premier par les effets du voyage, le second par ceux du tems ont été enlevés du bois sur lequel ils etaient transportés sur une autre toile et restaurés par les soins de l'aministration. </sentence>
        </part>
    </body>
</element>
